<?php
namespace Aspose\Slides\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class ColorScheme {
	static $swaggerTypes = array(
		'Accent1' => 'string',
		'Accent2' => 'string',
		'Accent3' => 'string',
		'Accent4' => 'string',
		'Accent5' => 'string',
		'Accent6' => 'string',
		'Dark1' => 'string',
		'Dark2' => 'string',
		'FollowedHyperlink' => 'string',
		'Hyperlink' => 'string',
		'Light1' => 'string',
		'Light2' => 'string',
		'SelfUri' => 'ResourceUri',
		'AlternateLinks' => 'array[ResourceUri]',
		'Links' => 'array[ResourceUri]'

	);

	public $Accent1; // string
	public $Accent2; // string
	public $Accent3; // string
	public $Accent4; // string
	public $Accent5; // string
	public $Accent6; // string
	public $Dark1; // string
	public $Dark2; // string
	public $FollowedHyperlink; // string
	public $Hyperlink; // string
	public $Light1; // string
	public $Light2; // string
	public $SelfUri; // ResourceUri
	public $AlternateLinks; // array[ResourceUri]
	public $Links; // array[ResourceUri]
	}

