<?php
namespace Aspose\Slides\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class FontSet {
	static $swaggerTypes = array(
		'ComplexScript' => 'string',
		'EastAsian' => 'string',
		'Latin' => 'string'

	);

	public $ComplexScript; // string
	public $EastAsian; // string
	public $Latin; // string
	}

