<?php
namespace Aspose\Slides\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class FontScheme {
	static $swaggerTypes = array(
		'Major' => 'FontSet',
		'Minor' => 'FontSet',
		'Name' => 'string',
		'SelfUri' => 'ResourceUri',
		'AlternateLinks' => 'array[ResourceUri]',
		'Links' => 'array[ResourceUri]'

	);

	public $Major; // FontSet
	public $Minor; // FontSet
	public $Name; // string
	public $SelfUri; // ResourceUri
	public $AlternateLinks; // array[ResourceUri]
	public $Links; // array[ResourceUri]
	}

