<?php
namespace Aspose\Slides\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class FormatSchemeResponse {
	static $swaggerTypes = array(
		'FormatScheme' => 'FormatScheme',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $FormatScheme; // FormatScheme
	public $Code; // string
	public $Status; // string
	}

