<?php
namespace Aspose\Slides\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class FormatScheme {
	static $swaggerTypes = array(
		'BackgroundStyles' => 'array[ResourceUri]',
		'EffectStyles' => 'array[ResourceUri]',
		'FillStyles' => 'array[ResourceUri]',
		'LineStyles' => 'array[ResourceUri]',
		'SelfUri' => 'ResourceUri',
		'AlternateLinks' => 'array[ResourceUri]',
		'Links' => 'array[ResourceUri]'

	);

	public $BackgroundStyles; // array[ResourceUri]
	public $EffectStyles; // array[ResourceUri]
	public $FillStyles; // array[ResourceUri]
	public $LineStyles; // array[ResourceUri]
	public $SelfUri; // ResourceUri
	public $AlternateLinks; // array[ResourceUri]
	public $Links; // array[ResourceUri]
	}

