<?php
namespace Aspose\Slides\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Image {
	static $swaggerTypes = array(
		'Width' => 'int',
		'Height' => 'int',
		'SelfUri' => 'ResourceUri',
		'AlternateLinks' => 'array[ResourceUri]',
		'Links' => 'array[ResourceUri]'

	);

	public $Width; // int
	public $Height; // int
	public $SelfUri; // ResourceUri
	public $AlternateLinks; // array[ResourceUri]
	public $Links; // array[ResourceUri]
	}

