<?php
namespace Aspose\Slides\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class OrderedMergeRequest {
	static $swaggerTypes = array(
		'Presentations' => 'array[PresentationToMerge]'

	);

	public $Presentations; // array[PresentationToMerge]
	}

