<?php
namespace Aspose\Slides\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Placeholder {
	static $swaggerTypes = array(
		'Index' => 'integer',
		'Orientation' => 'PlaceholderOrientation',
		'Size' => 'PlaceholderSize',
		'Type' => 'PlaceholderType',
		'Shape' => 'ResourceUriElement',
		'SelfUri' => 'ResourceUri',
		'AlternateLinks' => 'array[ResourceUri]',
		'Links' => 'array[ResourceUri]'

	);

	public $Index; // integer
	public $Orientation; // PlaceholderOrientation
	public $Size; // PlaceholderSize
	public $Type; // PlaceholderType
	public $Shape; // ResourceUriElement
	public $SelfUri; // ResourceUri
	public $AlternateLinks; // array[ResourceUri]
	public $Links; // array[ResourceUri]
	}

