<?php
namespace Aspose\Slides\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class PlaceholdersResponse {
	static $swaggerTypes = array(
		'Placeholders' => 'Placeholders',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $Placeholders; // Placeholders
	public $Code; // string
	public $Status; // string
	}

