<?php
namespace Aspose\Slides\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class PlaceholderResponse {
	static $swaggerTypes = array(
		'Placeholder' => 'Placeholder',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $Placeholder; // Placeholder
	public $Code; // string
	public $Status; // string
	}

