<?php
namespace Aspose\Slides\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Portion {
	static $swaggerTypes = array(
		'Text' => 'string',
		'FontColor' => 'string',
		'FontHeight' => 'float',
		'SelfUri' => 'ResourceUri',
		'AlternateLinks' => 'array[ResourceUri]',
		'Links' => 'array[ResourceUri]'

	);

	public $Text; // string
	public $FontColor; // string
	public $FontHeight; // float
	public $SelfUri; // ResourceUri
	public $AlternateLinks; // array[ResourceUri]
	public $Links; // array[ResourceUri]
	}

