<?php
namespace Aspose\Slides\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class PresentationsMergeRequest {
	static $swaggerTypes = array(
		'PresentationPaths' => 'array[string]'

	);

	public $PresentationPaths; // array[string]
	}

