<?php
namespace Aspose\Slides\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class PresentationToMerge {
	static $swaggerTypes = array(
		'Path' => 'string',
		'Slides' => 'array[int]'

	);

	public $Path; // string
	public $Slides; // array[int]
	}

