<?php
namespace Aspose\Slides\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class ResourceUri {
	static $swaggerTypes = array(
		'Href' => 'string',
		'Relation' => 'string',
		'LinkType' => 'string',
		'Title' => 'string'

	);

	public $Href; // string
	public $Relation; // string
	public $LinkType; // string
	public $Title; // string
	}

