<?php
namespace Aspose\Slides\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Shape {
	static $swaggerTypes = array(
		'Text' => 'string',
		'Paragraphs' => 'ResourceUriElement',
		'ShapeType' => 'AutoShapeType',
		'Name' => 'string',
		'Width' => 'float',
		'Height' => 'float',
		'AlternativeText' => 'string',
		'Hidden' => 'bool',
		'X' => 'float',
		'Y' => 'float',
		'ZOrderPosition' => 'int',
		'Shapes' => 'ResourceUriElement',
		'FillFormat' => 'ResourceUriElement',
		'LineFormat' => 'ResourceUriElement',
		'SelfUri' => 'ResourceUri',
		'AlternateLinks' => 'array[ResourceUri]',
		'Links' => 'array[ResourceUri]'

	);

	public $Text; // string
	public $Paragraphs; // ResourceUriElement
	public $ShapeType; // AutoShapeType
	public $Name; // string
	public $Width; // float
	public $Height; // float
	public $AlternativeText; // string
	public $Hidden; // bool
	public $X; // float
	public $Y; // float
	public $ZOrderPosition; // int
	public $Shapes; // ResourceUriElement
	public $FillFormat; // ResourceUriElement
	public $LineFormat; // ResourceUriElement
	public $SelfUri; // ResourceUri
	public $AlternateLinks; // array[ResourceUri]
	public $Links; // array[ResourceUri]
	}

