<?php
namespace Aspose\Slides\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class ShapeListResponse {
	static $swaggerTypes = array(
		'ShapeList' => 'Shapes',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $ShapeList; // Shapes
	public $Code; // string
	public $Status; // string
	}

