<?php
namespace Aspose\Slides\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class SlideComment {
	static $swaggerTypes = array(
		'Author' => 'string',
		'Text' => 'string',
		'CreatedTime' => 'string'

	);

	public $Author; // string
	public $Text; // string
	public $CreatedTime; // string
	}

