<?php
namespace Aspose\Slides\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class SlideCommentsResponse {
	static $swaggerTypes = array(
		'SlideComments' => 'SlideComments',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $SlideComments; // SlideComments
	public $Code; // string
	public $Status; // string
	}

