<?php
namespace Aspose\Slides\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class SlideBackgroundResponse {
	static $swaggerTypes = array(
		'Background' => 'SlideBackground',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $Background; // SlideBackground
	public $Code; // string
	public $Status; // string
	}

