<?php
namespace Aspose\Slides\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Slide {
	static $swaggerTypes = array(
		'Width' => 'float',
		'Height' => 'float',
		'Shapes' => 'ResourceUriElement',
		'Theme' => 'ResourceUriElement',
		'Placeholders' => 'ResourceUriElement',
		'Images' => 'ResourceUriElement',
		'Comments' => 'ResourceUriElement',
		'Background' => 'ResourceUriElement',
		'SelfUri' => 'ResourceUri',
		'AlternateLinks' => 'array[ResourceUri]',
		'Links' => 'array[ResourceUri]'

	);

	public $Width; // float
	public $Height; // float
	public $Shapes; // ResourceUriElement
	public $Theme; // ResourceUriElement
	public $Placeholders; // ResourceUriElement
	public $Images; // ResourceUriElement
	public $Comments; // ResourceUriElement
	public $Background; // ResourceUriElement
	public $SelfUri; // ResourceUri
	public $AlternateLinks; // array[ResourceUri]
	public $Links; // array[ResourceUri]
	}

