<?php
namespace Aspose\Slides\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class SlideListResponse {
	static $swaggerTypes = array(
		'Slides' => 'Slides',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $Slides; // Slides
	public $Code; // string
	public $Status; // string
	}

