<?php
namespace Aspose\Slides\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class SplitDocumentResult {
	static $swaggerTypes = array(
		'Slides' => 'array[ResourceUri]',
		'SelfUri' => 'ResourceUri',
		'AlternateLinks' => 'array[ResourceUri]',
		'Links' => 'array[ResourceUri]'

	);

	public $Slides; // array[ResourceUri]
	public $SelfUri; // ResourceUri
	public $AlternateLinks; // array[ResourceUri]
	public $Links; // array[ResourceUri]
	}

