<?php
namespace Aspose\Slides\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class TextItem {
	static $swaggerTypes = array(
		'Uri' => 'ResourceUri',
		'Text' => 'string'

	);

	public $Uri; // ResourceUri
	public $Text; // string
	}

