<?php
namespace Aspose\Slides\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Theme {
	static $swaggerTypes = array(
		'Name' => 'string',
		'ColorScheme' => 'ResourceUriElement',
		'FontScheme' => 'ResourceUriElement',
		'FormatScheme' => 'ResourceUriElement',
		'SelfUri' => 'ResourceUri',
		'AlternateLinks' => 'array[ResourceUri]',
		'Links' => 'array[ResourceUri]'

	);

	public $Name; // string
	public $ColorScheme; // ResourceUriElement
	public $FontScheme; // ResourceUriElement
	public $FormatScheme; // ResourceUriElement
	public $SelfUri; // ResourceUri
	public $AlternateLinks; // array[ResourceUri]
	public $Links; // array[ResourceUri]
	}

