<?php
namespace Aspose\Slides\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class ThemeResponse {
	static $swaggerTypes = array(
		'Theme' => 'Theme',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $Theme; // Theme
	public $Code; // string
	public $Status; // string
	}

